# Generated by Django 4.1.7 on 2023-03-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
