# Generated by Django 4.1.7 on 2023-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0006_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='votos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
