# Generated by Django 4.1.7 on 2023-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0008_alter_aluno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=100),
        ),
    ]
