# Generated by Django 4.1.7 on 2023-03-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0009_aluno_grupo_alter_aluno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='grupo',
        ),
    ]
