# Generated by Django 4.1.7 on 2023-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0010_remove_aluno_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
