# Generated by Django 4.1.7 on 2023-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0011_aluno_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
